spring.application.name=auth-service

server.port=8081

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
security.jwt.private-key=${PATH_PRIVATE_KEY}
security.jwt.public-key=${PATH_PUBLIC_KEY}
security.jwt.expiration=3600

# RabbitMQ - CloudAMQP
spring.rabbitmq.addresses=${RABBIT_ADDRESSES}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}
spring.rabbitmq.virtual-host=${RABBIT_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html